import type { Locale } from "@/lib/site";
import type { ProviderCategory } from "@/db/schema";

export interface CategoryCopy {
  title: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  pick: string;
}

export const categoryContent: Record<Locale, Record<ProviderCategory, CategoryCopy>> = {
  en: {
    erp: {
      title: "ERP-focused e-invoicing providers",
      metaTitle: "ERP E-Invoicing Providers UAE: SAP, Oracle & Dynamics ASPs",
      metaDescription:
        "Pre-approved UAE e-invoicing providers with deep ERP integration practices — SAP, Oracle, Microsoft Dynamics and enterprise landscapes. Compare and get matched free.",
      intro:
        "These pre-approved providers specialise in connecting enterprise resource planning systems — SAP, Oracle, Microsoft Dynamics and comparable estates — to the UAE's Electronic Invoicing System. Expect packaged connectors, middleware experience and structured implementation programmes rather than plug-and-play apps.",
      pick: "Shortlist here if your invoices are generated by an ERP and your project involves IT, finance and often an implementation partner.",
    },
    "tax-tech": {
      title: "Tax technology e-invoicing providers",
      metaTitle: "Tax-Tech E-Invoicing Providers UAE: Compliance-First ASPs",
      metaDescription:
        "UAE pre-approved ASPs built around tax compliance platforms — e-invoicing, VAT reporting and regulatory tech, many with ZATCA (Saudi) track records. Compare free.",
      intro:
        "Tax-technology providers approach e-invoicing from the compliance side: their platforms typically combine invoice clearance, VAT logic and regulatory reporting, and many operate across multiple mandates in the region — Saudi Arabia's ZATCA regime in particular.",
      pick: "Shortlist here if you want compliance depth, multi-country coverage, or a partner your tax team (not just IT) will work with daily.",
    },
    consulting: {
      title: "Consulting-led e-invoicing providers",
      metaTitle: "Consulting E-Invoicing Providers UAE: Advisory-Led ASPs",
      metaDescription:
        "Pre-approved UAE e-invoicing providers with strong advisory arms — implementation guidance, tax advice and managed compliance alongside the platform. Compare free.",
      intro:
        "These providers pair the accredited platform with hands-on advisory: scoping, data cleanup, process redesign and ongoing managed compliance. Several are the technology arms of established accounting and advisory groups.",
      pick: "Shortlist here if you want a partner to run the project with you, not just software to integrate against.",
    },
    "edi-network": {
      title: "EDI & network e-invoicing providers",
      metaTitle: "EDI & Peppol Network E-Invoicing Providers UAE",
      metaDescription:
        "UAE pre-approved ASPs with EDI and Peppol network heritage — high-volume document exchange, supply-chain integrations and international interoperability. Compare free.",
      intro:
        "Network and EDI providers have been moving structured business documents between trading partners for decades. They bring high-volume pipelines, supply-chain integrations and deep Peppol operating experience to the UAE mandate.",
      pick: "Shortlist here if you exchange large document volumes, run EDI with retailers or logistics partners, or invoice across borders.",
    },
    "enterprise-software": {
      title: "Enterprise software e-invoicing providers",
      metaTitle: "Enterprise Software E-Invoicing Providers UAE",
      metaDescription:
        "Pre-approved UAE ASPs from established enterprise software vendors — broad product suites, regional presence and large-organisation support models. Compare free.",
      intro:
        "These are established software houses whose product suites extend well beyond invoicing — and whose UAE accreditation adds compliant e-invoicing to a broader enterprise stack with mature support organisations behind it.",
      pick: "Shortlist here if you prefer a large-vendor relationship, existing regional support, and one contract covering more than e-invoicing.",
    },
    fintech: {
      title: "Fintech e-invoicing providers",
      metaTitle: "Fintech E-Invoicing Providers UAE: Modern API-First ASPs",
      metaDescription:
        "UAE pre-approved fintech ASPs — API-first platforms, fast onboarding and modern dashboards, often with payments and financing angles. Compare and get matched free.",
      intro:
        "Fintech providers bring modern, API-first platforms to the mandate: quick onboarding, clean dashboards, and in several cases adjacent services like payments, receivables financing or spend management.",
      pick: "Shortlist here if you value speed of onboarding, developer-friendly APIs, or want invoicing connected to payments and cash flow.",
    },
  },
  ar: {
    erp: {
      title: "مزودو الفوترة الإلكترونية المتخصصون في أنظمة ERP",
      metaTitle: "مزودو الفوترة الإلكترونية لأنظمة ERP في الإمارات: SAP وOracle وDynamics",
      metaDescription:
        "مزودون معتمدون مبدئياً في الإمارات بخبرات تكامل عميقة مع أنظمة تخطيط الموارد — SAP وOracle وMicrosoft Dynamics والبيئات المؤسسية. قارن واحصل على مطابقة مجانية.",
      intro:
        "يتخصص هؤلاء المزودون المعتمدون مبدئياً في ربط أنظمة تخطيط موارد المؤسسات — SAP وOracle وMicrosoft Dynamics وما يماثلها — بنظام الفوترة الإلكترونية الإماراتي. توقع موصلات جاهزة وخبرة وسيطات تكامل وبرامج تطبيق منظمة، لا تطبيقات جاهزة للتوصيل فحسب.",
      pick: "اختر من هنا إذا كانت فواتيرك تصدر من نظام ERP ومشروعك يشمل تقنية المعلومات والمالية وغالباً شريك تنفيذ.",
    },
    "tax-tech": {
      title: "مزودو الفوترة الإلكترونية من شركات التقنية الضريبية",
      metaTitle: "مزودو التقنية الضريبية للفوترة الإلكترونية في الإمارات",
      metaDescription:
        "مزودون معتمدون مبدئياً في الإمارات بمنصات امتثال ضريبي — فوترة إلكترونية وتقارير ضريبة القيمة المضافة، وكثير منهم بخبرة نظام «فاتورة» السعودي. قارن مجاناً.",
      intro:
        "يقارب مزودو التقنية الضريبية الفوترة الإلكترونية من جهة الامتثال: تجمع منصاتهم عادة بين اعتماد الفواتير ومنطق ضريبة القيمة المضافة والتقارير التنظيمية، ويعمل كثير منهم عبر عدة أنظمة إلزام في المنطقة — وعلى رأسها نظام هيئة الزكاة والضريبة والجمارك السعودية.",
      pick: "اختر من هنا إذا أردت عمقاً في الامتثال أو تغطية متعددة الدول أو شريكاً يتعامل معه فريقك الضريبي يومياً لا التقني فقط.",
    },
    consulting: {
      title: "مزودو الفوترة الإلكترونية بقيادة استشارية",
      metaTitle: "مزودو الفوترة الإلكترونية الاستشاريون في الإمارات",
      metaDescription:
        "مزودون معتمدون مبدئياً في الإمارات بأذرع استشارية قوية — إرشاد في التطبيق واستشارات ضريبية وامتثال مُدار إلى جانب المنصة. قارن مجاناً.",
      intro:
        "يجمع هؤلاء المزودون بين المنصة المعتمدة والاستشارة العملية: تحديد النطاق وتنظيف البيانات وإعادة تصميم العمليات والامتثال المدار المستمر. وعدد منهم الأذرع التقنية لمجموعات محاسبة واستشارات راسخة.",
      pick: "اختر من هنا إذا أردت شريكاً يدير المشروع معك، لا برنامجاً تتكامل معه فحسب.",
    },
    "edi-network": {
      title: "مزودو الفوترة الإلكترونية من شبكات EDI",
      metaTitle: "مزودو شبكات EDI وPeppol للفوترة الإلكترونية في الإمارات",
      metaDescription:
        "مزودون معتمدون مبدئياً بإرث في شبكات EDI وPeppol — تبادل مستندات عالي الحجم وتكاملات سلاسل الإمداد وقابلية تشغيل دولية. قارن مجاناً.",
      intro:
        "ينقل مزودو الشبكات وEDI المستندات التجارية المنظمة بين الشركاء التجاريين منذ عقود، ويجلبون إلى الإلزام الإماراتي خطوط معالجة عالية الحجم وتكاملات سلاسل الإمداد وخبرة تشغيل عميقة في Peppol.",
      pick: "اختر من هنا إذا كنت تتبادل أحجام مستندات كبيرة أو تدير EDI مع تجار التجزئة أو الشركاء اللوجستيين أو تفوتر عبر الحدود.",
    },
    "enterprise-software": {
      title: "مزودو الفوترة الإلكترونية من شركات البرمجيات المؤسسية",
      metaTitle: "مزودو البرمجيات المؤسسية للفوترة الإلكترونية في الإمارات",
      metaDescription:
        "مزودون معتمدون مبدئياً من دور برمجيات مؤسسية راسخة — حزم منتجات واسعة وحضور إقليمي ونماذج دعم للمؤسسات الكبيرة. قارن مجاناً.",
      intro:
        "هذه دور برمجيات راسخة تمتد حزم منتجاتها إلى ما هو أبعد من الفوترة — ويضيف اعتمادها الإماراتي فوترة إلكترونية ممتثلة إلى منظومة مؤسسية أوسع تسندها مؤسسات دعم ناضجة.",
      pick: "اختر من هنا إذا كنت تفضل علاقة مع مورد كبير ودعماً إقليمياً قائماً وعقداً واحداً يغطي أكثر من الفوترة الإلكترونية.",
    },
    fintech: {
      title: "مزودو الفوترة الإلكترونية من شركات التقنية المالية",
      metaTitle: "مزودو التقنية المالية للفوترة الإلكترونية في الإمارات",
      metaDescription:
        "مزودو تقنية مالية معتمدون مبدئياً في الإمارات — منصات قائمة على الواجهات البرمجية وتأهيل سريع ولوحات حديثة، وغالباً بزوايا مدفوعات وتمويل. قارن مجاناً.",
      intro:
        "يجلب مزودو التقنية المالية منصات حديثة قائمة على الواجهات البرمجية إلى الإلزام: تأهيل سريع ولوحات واضحة، وفي حالات عدة خدمات مجاورة كالمدفوعات وتمويل الذمم وإدارة الإنفاق.",
      pick: "اختر من هنا إذا كنت تقدّر سرعة التأهيل والواجهات الصديقة للمطورين أو تريد ربط الفوترة بالمدفوعات والتدفق النقدي.",
    },
  },
};
